[Unit]
Description = "Console login (rgetty)"
Name = "console-shell"

[Service]
Type = "simple"
# 完整命令直接传 getty 参数：-L（CLOCAL）、-t 60（超时）、ttyAMA0（登录终端）
ExecStart = "/bin/rgetty -L -t 60 ttyAMA0"
Console = true

[Install]
WantedBy = ["default.target"]